DATASET:
  NAME: "build_coco_dataset"
  TRAIN: 
    ANNOTATION: "datasets/COCO/kitti_train.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOBBoxResize:
        INPUT_SIZE: &INPUT_SIZE [384, 1152]

  VAL: 
    ANNOTATION: &VAL_ANNOTATION "datasets/COCO/kitti_val.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOResize:
        INPUT_SIZE: *INPUT_SIZE
      
  TEST: 
    ANNOTATION: "datasets/COCO/kitti_val.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOResize:
        INPUT_SIZE: *INPUT_SIZE

DATALOADER:
  TRAIN:
    BATCH_SIZE: 16
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTrainCollator"
      PIXEL_MEAN: &PIXEL_MEAN [0.40789654, 0.44719302, 0.47026115]
      PIXEL_STD: &PIXEL_STD [0.28863828, 0.27408164, 0.27809835]

  VAL:
    BATCH_SIZE: 32
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOValCollator"
      PIXEL_MEAN: *PIXEL_MEAN
      PIXEL_STD: *PIXEL_STD

  TEST:
    BATCH_SIZE: 32
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTestCollator"
      PIXEL_MEAN: *PIXEL_MEAN
      PIXEL_STD: *PIXEL_STD

MODEL:
  META_ARCHITECTURE: "CenterNet"
  MODULES:
    -
      NAME: "DLASeg"
      base_name: "dla34"
      conv_name: "DCNV2"
      pretrained: "data/dla34-ba72cf86.pth"
    -
      NAME: "CenterNetHead"
      in_channels: 64
      branches:
        -
          name: "hm"
          head_channels: 256
          out_channels: &NUM_CLASSES 3
          prior_bias: -2.19
        -
          name: "wh"
          head_channels: 256
          out_channels: 2
        -
          name: "reg"
          head_channels: 256
          out_channels: 2
  OUTPUT_NAMES: ["hm", "wh", "reg"]
  PREDICT:
    NAME: "ctdet_predict"
    DOWN_RATIO: &DOWN_RATIO 4
    NUM_CLASSES: *NUM_CLASSES
    NUM_OUTPUTS: 100
    SCORE_THRESHOLDS: [0.1, 0.1, 0.1]
    OUTPUT_SIZE: &OUTPUT_SIZE [96, 288]

CRITERION:
  NAME: "CenterNetDetCriterion"
  DOWN_RATIO: *DOWN_RATIO
  OUTPUT_SIZE: *OUTPUT_SIZE
  NUM_CLASSES: *NUM_CLASSES
  HEATMAP_LOSS_TYPE: "focal_loss"
  REG_LOSS_TYPE: "l1"
  SIZE_LOSS_TYPE: "l1"
  HEATMAP_LOSS_WEIGHT: 1
  REG_LOSS_WEIGHT: 1
  SIZE_LOSS_WEIGHT: 0.1
  MIN_OVERLAP: 0.7
  NUM_OUTPUTS: 128
  
SOLVER:
  MAX_EPOCHS: 60
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  NESTEROV: False

MISC:
  WITH_AMP: False
  ASP: False

EVALUATOR:
  NAME: "COCOEvaluator"
  VAL_OUTPUT: "data/outputs"
  MAX_DETS: 100
  ANNOTATION: *VAL_ANNOTATION
  INPUT_SIZE: *OUTPUT_SIZE
  INTERVAL: 5
  METRIC_NAME: &METRIC_NAME "AP"

VISUALIZE:
  NAME: CenterNetDetVisualizer
  NUM_SAMPLES: 1
  NUM_IMAGES: 4
  CLASSES_NAME: ["Car", "Cyclist", "Pedestrian"]
  CLASSES_COLOR: [
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255]
  ]
  INPUT_SIZE: *OUTPUT_SIZE
  
SAVE:
  OUTPUT_PATH: "data/1112_cd"
  VAL_SCORE: *METRIC_NAME
  RESUME: null
  NUM_CHECKPOINTS: 20
  INTERVAL: 2
  PTQ: null
