INPUT_IMAGE_SIZE: &INPUT_SIZE [320, 1152]

DATASET:
  NAME: "build_coco_dataset"
  TRAIN: 
    ANNOTATION: "datasets/COCO/kitti_train.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOBBoxResize:
        INPUT_SIZE: *INPUT_SIZE
      
  TEST: 
    ANNOTATION: "datasets/COCO/kitti_val.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOResize:
        INPUT_SIZE: *INPUT_SIZE

DATALOADER:
  TRAIN:
    BATCH_SIZE: 8
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTrainCollator"
      PIXEL_MEAN: [0.485, 0.456, 0.406]
      PIXEL_STD: [0.229, 0.224, 0.225]
  TEST:
    BATCH_SIZE: 16
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTestCollator"
      PIXEL_MEAN: [0.485, 0.456, 0.406]
      PIXEL_STD: [0.229, 0.224, 0.225]

MODEL:
  META_ARCHITECTURE: "RetinaNet"
  MODULES:
    -
      NAME: "MobileNetV3"

    -
      NAME: "BiFPN"

    -
      NAME: "RetinaNetHead"
  ANCHOR_GENERATOR:
    OFFSET: 0.5
    SIZES: [
      [32, 46.151986249837066, 66.56268233766093],
      [96, 138.45595874951118, 199.6880470129828],
      [320, 461.5198624983707, 665.6268233766093]
    ]
    ASPECT_RATIOS: [
      [0.5, 1., 2.],
      [0.5, 1., 2.],
      [0.5, 1., 2.]
    ]