INPUT_IMAGE_SIZE: &INPUT_SIZE [384, 1152]

DATASET:
  NAME: "build_coco_dataset"
  TRAIN: 
    ANNOTATION: "datasets/COCO/kitti_train.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOBBoxResize:
        INPUT_SIZE: *INPUT_SIZE
      
  TEST: 
    ANNOTATION: "datasets/COCO/kitti_val.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOResize:
        INPUT_SIZE: *INPUT_SIZE

DATALOADER:
  TRAIN:
    BATCH_SIZE: 8
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTrainCollator"
      PIXEL_MEAN: [0.485, 0.456, 0.406]
      PIXEL_STD: [0.229, 0.224, 0.225]
  TEST:
    BATCH_SIZE: 16
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTestCollator"
      PIXEL_MEAN: [0.485, 0.456, 0.406]
      PIXEL_STD: [0.229, 0.224, 0.225]

MODEL:
  META_ARCHITECTURE: "RetinaNet"
  MODULES:
    -
      NAME: "MobileNetV3"
      pretrained: "data/mobilenet_v3_small-047dcff4.pth"
      base_channels: 16
      inverted_residuals:
        - [16, 3, 16, 16, True, False, 2, 1]
        - [16, 3, 72, 24, False, False, 2, 1]
        - [24, 3, 88, 24, False, False, 1, 1]
        - [24, 5, 96, 40, True, False, 2, 1]
        - [40, 5, 240, 40, True, False, 1, 1]
        - [40, 5, 240, 40, True, False, 1, 1]
        - [40, 5, 120, 48, True, False, 1, 1]
        - [48, 5, 144, 48, True, False, 1, 1]
        - [48, 5, 288, 96, True, False, 2, 1]
        - [96, 5, 576, 96, True, False, 1, 1]
        - [96, 5, 576, 96, True, False, 1, 1]
      out_features: [3, 8, 11]
      freeze_at: -1
    -
      NAME: "BiFPN"
      conv_channels: [24, 48, 96]
      num_channels: 48
    -
      NAME: "RetinaNetHead"
      shared: False
      num_classes: 3
      num_anchors: 9
      conv_channels:
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]

  ANCHOR_GENERATOR:
    OFFSET: 0.5
    SIZES: [
      [32, 46.151986249837066, 66.56268233766093],
      [96, 138.45595874951118, 199.6880470129828],
      [320, 461.5198624983707, 665.6268233766093]
    ]
    ASPECT_RATIOS: [
      [0.5, 1., 2.],
      [0.5, 1., 2.],
      [0.5, 1., 2.]
    ]
  
  PREDICT:
    NUM_OUTPUTS: 100
    SCORE_THRESHOLD: 0.1
    IOU_THRESHOLD: 0.5

CRITERION:
  NAME: "RetinaNetCriterion"
  IOU_THRESHOLDS:
    - [0.4, 0.5]
    - [0.4, 0.5]
    - [0.4, 0.5]
  FOCAL_LOSS_GAMMA: 2.0
  FOCAL_LOSS_ALPHA: 0.25
  BBOX_REG_LOSS_TYPE: "smooth_l1"
  SMOOTH_L1_LOSS_BETA: 0.1
  