ANCHOR_GENERATOR: &ANCHORS
  offset: 0.5
  sizes: [
    [32., 40.3174736, 50.79683366],
    [64., 80.63494719, 101.59366733],
    [128., 161.26989439, 203.18733465],
    [256., 322.53978877, 406.3746693],
    [512., 645.07957755, 812.74933861]
  ]
  aspect_ratios: [
    [0.5, 1., 2.],
    [0.5, 1., 2.],
    [0.5, 1., 2.],
    [0.5, 1., 2.],
    [0.5, 1., 2.]
  ]
  features_spatial: [
    [48, 144],
    [24, 72],
    [12, 36],
    [6, 18],
    [3, 9]
  ]
  strides: [8, 16, 32, 64, 128]

DATASET:
  NAME: "build_coco_dataset"
  TRAIN: 
    ANNOTATION: "datasets/COCO/kitti_train.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOBBoxResize:
        INPUT_SIZE: &INPUT_SIZE [384, 1152]
      
  TEST: 
    ANNOTATION: &TEST_ANNOTATION "datasets/COCO/kitti_val.json"
    TRANSFORMS:
      COCOLoadImage: null
      COCOResize:
        INPUT_SIZE: *INPUT_SIZE

DATALOADER:
  TRAIN:
    BATCH_SIZE: 8
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTrainCollator"
      PIXEL_MEAN: [0.485, 0.456, 0.406]
      PIXEL_STD: [0.229, 0.224, 0.225]
  TEST:
    BATCH_SIZE: 16
    NUM_WORKERS: 8
    COLLATE_FN:
      NAME: "COCOTestCollator"
      PIXEL_MEAN: [0.485, 0.456, 0.406]
      PIXEL_STD: [0.229, 0.224, 0.225]

MODEL:
  META_ARCHITECTURE: "RetinaNet"
  MODULES:
    -
      NAME: "MobileNetV3"
      pretrained: "data/mobilenet_v3_small-047dcff4.pth"
      base_channels: 16
      inverted_residuals:
        - [16, 3, 16, 16, True, False, 2, 1]
        - [16, 3, 72, 24, False, False, 2, 1]
        - [24, 3, 88, 24, False, False, 1, 1]
        - [24, 5, 96, 40, True, False, 2, 1]
        - [40, 5, 240, 40, True, False, 1, 1]
        - [40, 5, 240, 40, True, False, 1, 1]
        - [40, 5, 120, 48, True, False, 1, 1]
        - [48, 5, 144, 48, True, False, 1, 1]
        - [48, 5, 288, 96, True, False, 2, 1]
        - [96, 5, 576, 96, True, False, 1, 1]
        - [96, 5, 576, 96, True, False, 1, 1]
      out_features: [3, 8, 11]
      out_names: ["p3", "p4", "p5"]
      freeze_at: -1
    -
      NAME: "BiFPN"
      conv_channels: [24, 48, 96]
      num_channels: 48
      in_names: ["p3", "p4", "p5"]
      out_names: ["p3", "p4", "p5", "p6", "p7"]
    -
      NAME: "RetinaNetHead"
      shared: False
      num_classes: &num_classes 3
      num_anchors: &num_anchors 9
      conv_channels:
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
        - [48, 48, 48, 48, 48]
      in_names: ["p3", "p4", "p5", "p6", "p7"]
      out_names: ["logits", "regress"]

  PREDICT:
    ANCHORS: *ANCHORS
    NUM_ANCHORS: *num_anchors
    NUM_CLASSES: *num_classes
    NUM_OUTPUTS: 100
    SCORE_THRESHOLDS: [0.1, 0.1, 0.1]
    IOU_THRESHOLD: 0.3
    INPUT_SIZE: *INPUT_SIZE 

CRITERION:
  NAME: "RetinaNetCriterion"
  IOU_THRESHOLDS:
    - [0.4, 0.5]
    - [0.4, 0.5]
    - [0.4, 0.5]
  FOCAL_LOSS_GAMMA: 2.0
  FOCAL_LOSS_ALPHA: 0.25
  BBOX_REG_LOSS_TYPE: "smooth_l1"
  ANCHORS: *ANCHORS
  NUM_CLASSES: *num_classes
  NUM_ANCHORS: *num_anchors
  
SOLVER:
  MAX_EPOCHS: 30
  BASE_LR: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  NESTEROV: False

MISC:
  WITH_AMP: False
  ASP: False

EVALUATOR:
  NAME: "COCOEvaluator"
  TEST_OUTPUT: "data/outputs"
  MAX_DETS: 100
  ANNOTATION: *TEST_ANNOTATION
  INPUT_SIZE: *INPUT_SIZE
  INTERVAL: 1
  METRIC_NAME: &METRIC_NAME "AP"

VISUALIZE:
  NAME: RetinaNetVisualizer
  NUM_SAMPLES: 1
  CLASSES_NAME: ["Car", "Cyclist", "Pedestrian"]
  CLASSES_COLOR: [
    [255, 0, 0],
    [0, 255, 0],
    [0, 0, 255]
  ]
  INPUT_SIZE: *INPUT_SIZE
  
SAVE:
  OUTPUT_PATH: "data/runs"
  TEST_SCORE: *METRIC_NAME
  RESUME: null
  NUM_CHECKPOINTS: 20
  INTERVAL: 5
